### ISSUE TITLE
Hot replacement, browser does not refresh after code recompiles

### ISSUE THREAD

**Issue by prawana-perera** [tomduncalf/ts-react-template#1]
Hi @tomduncalf,

Thanks so much for the tutorial and template project. One thing I found was the the browser did not refresh after hot replacement code changes were made. This was because the hot=true was set in the server.js as well as in the webpack config. I think the doco says only set it in one place. I commented out the "hot: true" from server.js and the browser reloaded with changes.

**Comment by tomduncalf** [comment]
Hi Prawana,

Thanks, I'm glad you found it useful! 

By "the browser did not refresh", do you mean actually refreshing the page, or that the components did not hot reload? You should not see a whole page reload, but you should see the components update in place while maintaining their state.

This worked for me on Chrome, although I haven't retested – what browser were you having issues with? I'll retest and if it is an issue, update the post and repo 

Cheers,
Tom

**Comment by prawana-perera** [comment]
Hi @tomduncalf,

Yes you are correct. It does work. I adapted your template and was adding some more feature, so something is incorrect with my setup. Closing issue.

Cheers.
