### ISSUE TITLE
NPM typings integration in VScode

### ISSUE THREAD

**Issue by luk-rs** [tomduncalf/ts-react-template#4]
Hi Tom,

First of all congratulations on the contribution, i was thinking of making something like this myself.
I've managed to run this flawlessly and it works like a charm.

I've just some questions regarding integration of typings into VScode.

In my case I can only have typings in the editor if I install them myself via typings, overloading the ones on node modules which doesnt seem correct. If I understood correctly after cloning the repo and installing npm dependencies this should work like a charm in VS code right?

I'll leave you some screenshots of the problems i have with react react-dom require and tsx components.

![image](https://cloud.githubusercontent.com/assets/2011030/18176583/1819083c-706e-11e6-9adb-4ad0a7855095.png)

![image](https://cloud.githubusercontent.com/assets/2011030/18176738/e7977f30-706e-11e6-9b94-99e854eaf42a.png)

Hope you can help me with this.

Thanks,
Luís

**Comment by tomduncalf** [comment]
Hey Luis,

Thanks for your kind words and I'm glad you found this useful :) I'm hoping
to find the time to update it to the 2.0 release version once that is out.

Regarding your problem – have you tried settings the typescript.tsdk for
your project as described in Stefan's comment at
http://blog.tomduncalf.com/posts/setting-up-typescript-and-react/#comment-2756511681?
This fixed the issue for me (you may need to restart Code).

Let me know if that doesn't work!

Thanks,
Tom

**Comment by luk-rs** [comment]
That was it :+1: , it is now working with intellisense as expected. Maybe you could update the readme file or the tutorial with this note! 

Thanks.

PS.: I am available to contribute if need any help. Plz feel free to contact me at santos8@gmail.com if you need anything.
